#!/usr/bin/env bash
# 2021-08-26   Inspired by WinGrid-antiX

PROGNAME=${0##*/}
PROGVERSION="0.1"

# --------------------
# Help and Information
# --------------------

# When requested show information about script
if [ "$1" = '-h' ] || [ "$1" = '--help' ]
then
   winmess-usage
   exit 0
fi



# --------------------------
# User Configurable Settings
# --------------------------

# Location of the user configurable settings file
CONFIGFILE="$HOME/.config/winmess.conf"

# Obtain the user specifiable configuration
if [ -f $CONFIGFILE ]; then
   . $CONFIGFILE

   else

   # Display an error message and exit
   ERRMSG=" $CONFIGFILE \n Was not found \n\n Exiting..."
   YADBOX="--title="WinMess" --image="error" --button="OK:1""
   [ "$DISPLAY" != "" ] && yad $YADBOX --text="$ERRMSG"
   exit 1
fi

# Guard against missing individual settings
[ "$WINHEIGHT_LESS" = "" ] && WINHEIGHT_LESS=0
[ "$WINHEIGHT_MORE" = "" ] && WINHEIGHT_MORE=0
[ "$GAPTOP" = "" ] && GAPTOP=0
[ "$GAPLEFT" = "" ] && GAPLEFT=0



# --------------------
# Construct Parameters
# --------------------

# Capture screen resolution value
SCREENRES=$(xdpyinfo | awk '/dimensions:/ { sub("x", " "); print $2" "$3 }')

# Extract screen resolution into height and width components
SCREENWIDTH=${SCREENRES% *}
SCREENHEIGHT=${SCREENRES#* }

# Calculate 50% of the screen width and height values
SCREENHALFWIDTH=$(($SCREENWIDTH/2))
SCREENHALFHEIGHT=$(($SCREENHEIGHT/2))

# Reference used by window manager when positioning the window (always zero)
GRAVITY=0

# Distance from screen top edge to top edge of centered window
OFFSETTOP=$(($SCREENHEIGHT/4))
OFFSETTOP=$(($OFFSETTOP+$GAPTOP))

# Distance from screen left edge to left edge of centered window
OFFSETLEFT=$(($SCREENWIDTH/4))
OFFSETLEFT=$(($OFFSETLEFT+$GAPLEFT))

# Dimensions of window
WINHEIGHT=$(($SCREENHALFHEIGHT-$WINHEIGHT_LESS))
WINWIDTH=$SCREENHALFWIDTH



# ----------------------------
# Put Window into Grid Pattern
# ----------------------------

# Ensure the active window is not in maximized mode nor in fullscreen mode
wmctrl -r :ACTIVE: -b remove,maximized_horz,maximized_vert
wmctrl -r :ACTIVE: -b remove,fullscreen

# Position and resize the active window
wmctrl -r :ACTIVE: -e $GRAVITY,$OFFSETLEFT,$OFFSETTOP,$WINWIDTH,$WINHEIGHT
