#!/usr/bin/env bash
# 2021-08-27   WinMess inspired by WinGrid-antiX
#              Place and resize active window.

PROGNAME="${0##*/}"
PROGDIR="${0%/*}"
PROGVERSION=$($PROGDIR/winmess-version)
LIBDIR="$PROGDIR/../lib"

# Location of utility functions.
LIBFILE="$LIBDIR/winmess-lib.sh"

# Load the utilities.
. $LIBFILE

# Initialize usage prompt.
init_help "$1"

# Location of the user configurable settings file.
CONFIGFILE="$HOME/.config/winmess.conf"

# Obtain the user specifiable configuration.
if [ -f $CONFIGFILE ]
then
    . $CONFIGFILE
else
    # Display an error message and exit.
    ERRMSG=" $CONFIGFILE \n Was not found \n\n Exiting..."
    error "$ERRMSG"
    exit 1
fi

# Get screen resolutions.
init_res

# Put Window into Grid Pattern
# ----------------------------

# Ensure the active window is not in maximized mode nor in fullscreen mode.
wmctrl -r :ACTIVE: -b remove,maximized_horz,maximized_vert
wmctrl -r :ACTIVE: -b remove,fullscreen

HINT_NAME="$1"
HINT_VALUE="${HINT[$HINT_NAME]}"

LEFT=$(field x "$HINT_VALUE")
TOP=$(field y "$HINT_VALUE")
WIDTH=$(field w "$HINT_VALUE")
HEIGHT=$(field h "$HINT_VALUE")

# Distance from screen top edge to top edge of the window.
OFFSETTOP=$(($TOP+$GAPTOP))

# Distance from screen left edge to left edge of the window.
OFFSETLEFT=$(($LEFT+$GAPLEFT))

# Dimensions of the window.
WINHEIGHT=$(($HEIGHT-$WINHEIGHT_LESS))
WINWIDTH=$WIDTH

# Position and resize the active window.
wmctrl -r :ACTIVE: -e $GRAVITY,$OFFSETLEFT,$OFFSETTOP,$WINWIDTH,$WINHEIGHT
